package com.aptatek.pkulab.domain.model.reader;

public enum  WorkflowState {

    DEFAULT,
    SELF_TEST,
    READING_CASSETTE,
    DETECTING_FLUID,
    USED_CASSETTE_ERROR,
    TEST_RUNNING,
    TEST_COMPLETE,
    POST_TEST,
    READY,
    CONTAMINATED_CASSETTE_ERROR,
    EXPIRED_CASSETTE_ERROR,
    ENVIRONMENT_ERROR,
    HARDWARE_ERROR,
    SYSTEM_ERROR,
    TEST_ERROR,
    TIME_ERROR,
    SYSTEM_MEMORY_ERROR,
    INVALID_CASSETTE_ERROR,
    FLUID_ALREADY_PRESENT_ERROR,
    FLUID_DETECTION_ERROR,
    POWER_ERROR,
    CASSETTE_REMOVED_ERROR
}
